### ISSUE TITLE
Unhelpful Accounts.onCreateUsers call

### ISSUE THREAD

**Issue by vuhpham** [djluck/azure-active-directory#1]
Hi @djluck, thank you for creating this cool package :+1: 
I just have one minor concern...Should we put onCreateUsers [https://github.com/djluck/azure-active-directory/blob/master/azure_ad_server.js#L5] to package? IMO, onCreateUsers can be called only once so it will be a limitation if we want not only azure sso but also facebook, twitter...

**Comment by djluck** [comment]
Hi @vuhpham, you raise a good point- I wasn't aware that Accounts.onCreateUsers() could only be called once. I'll remove this call and modify the documentation in accounts-azure-active-directory to point out that it is possible to capture the email address of Azure AD accounts. Sound good?

**Comment by vuhpham** [comment]
Awesome, thank @djluck :+1:
