### ISSUE TITLE
Don't set email address

### ISSUE THREAD

**Issue by dburles** [djluck/azure-active-directory#4]
https://github.com/djluck/azure-active-directory/blob/master/azure_ad_server.js#L34-L39

Hey @djluck I don't believe it's correct to set the email address here (no core accounts packages do this).

**Comment by djluck** [comment]
Good morning @dburles,

You're right (about no other core accounts package doing this), but I included it for two reasons:
1. I think this behavior is helpful to meteor developers (I certainly found it useful- now I can send emails to users by looking at their options.emails value). 
2. I'm not aware of any documentation or practice explicitly against storing the email address here. 

If you can think of a good case to remove this information, I'm all ears :)

Cheers,

James

**Comment by dburles** [comment]
I'm not sure exactly why they don't set the email address, though the problem I'm facing here is when linking oauth services to a password account, we wouldn't wish for the existing email address to be overwritten.

Just another question actually noticed that you have `graphUser.mail || graphUser.userPrincipleName;` it appears as though it's possible to have an account without an email address associated or if it's not under `mail` it's then found under `userPrincipleName`, reason I ask is that I've gone with that logic in order to retrieve the email address directly off the service information on the user document.

**Comment by djluck** [comment]
How are you linking the accounts? Is this functionality provided by meteor?

As for `graphUser.mail || graphUser.userPrincipleName;`, this was based on my testing against the office365 tennant I have access to, NOT documentation (when I wrote this, I couldn't find any documentation about when these fields would be available however this may have changed).

**Comment by dburles** [comment]
It's not something that is provided by core but there's been requests for it, I'm using a package https://github.com/yubozhao/meteor-link-accounts and here's the PR https://github.com/meteor/meteor/pull/1133

Ah thanks, I'll have a dig through the docs, will let you know if I find something concrete.

**Comment by djluck** [comment]
Perhaps because most of the auth packages don't include the `options.emails` field, the package your using to merge user accounts isn't merging this array correctly. I haven't looked through the code but it seems like this would be the likely culprit (additionally it should be noted that `azure_ad_server.js` just returns an object to customize a new user, it doesn't explicitly overwrite the `emails` field).

**Comment by djluck** [comment]
Hey @dburles, did you have any success?
